version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: voice-recorder-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voice_db
      MYSQL_USER: voiceuser
      MYSQL_PASSWORD: voicepass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - voice-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voice-recorder-backend
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=voice_db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mysql
    networks:
      - voice-network
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voice-recorder-frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - voice-network

volumes:
  mysql-data:

networks:
  voice-network:
    driver: bridge
